[pytest]
addopts = --import-mode=importlib
testpaths =
    mujoco_scenes/tests
    mujoco_scenes/functional_tamp_pipeline/tests
    inference_server
    perception_server
    llm3_baseline/tests
    vlm_tamp_baseline/tests
    owl_tamp_baseline/tests
    baseline_common/tests
